---
title: "Comparing Clustering Methods on 2-Cluster Mixed Data"
output: rmarkdown::github_document
date: '2022-09-08'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.retina = 2)
```


The goal of the project was to compare established methods of clustering mixed data (data with both continuous and categorical variables) to our implementation of spectral clustering for mixed data.

The established methods chosen were `KAMILA` and `kprototypes`.

```{r}

rm(list = ls())
gc()

# Load KAMILA and kprototypes
library(kamila) # kamila
library(clustMixType) # kproto
library(MixGHD) # ARI

# load functions for mixed data generation

file_to_load <- "/Users/felix.mbuga/Library/Mobile Documents/com~apple~CloudDocs/GitHub/projects/Clustering/functions_gen_2_clusters.R"
source(file_to_load)
ls()

# load function for spectral clustering of mixed data

file_to_load <- "/Users/felix.mbuga/Library/Mobile Documents/com~apple~CloudDocs/GitHub/projects/Clustering/function_speClusMixed.R"
source(file_to_load)
ls()

```

Generate dataset and visualize

```{r}

z <- gen_2_clusters_mixed(seed = sample(1000, 1))
str(z)

pairs(~ ., col = z$labels, data = z$data)

```


Cluster dataset with `kamila` and with `kproto`

```{r}

z_kam <- kamila(Filter(is.numeric, z$data), Filter(is.factor, z$data), numClust = 2, numInit = 100)
print(paste('kamila ARI:', round(ARI(z$labels, z_kam$finalMemb), 3)))

z_kproto <-kproto(z$data, k = 2, nstart = 100, verbose = FALSE)
print(paste('kproto ARI:', round(ARI(z$labels, z_kproto$cluster), 3)))

z_speclus <- speClusMixed(z)
print(paste('speclus ARI:', round(z_speclus$ARI['ARI'], 3)))

```



Session info

```{r}

R.Version()
R.version
version
sessionInfo()

```
